[package]
name = "rlox"
version = "0.1.0"
authors = ["Daniel Hofstetter <daniel.hofstetter@42dh.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
